### ISSUE TITLE
Not working with Rails 4.1.0

### ISSUE THREAD

**Issue by devilankur18** [charliesome/better_errors#243]
I have upgraded my app from 4.0.x to 4.1.0 and after that better error stopped working. Anyone faces similar issues ?

**Comment by vitaly** [comment]
having the same problem, `rails c` crashes with

    /usr/local/rvm/gems/ruby-2.1.5/gems/honeybadger-1.15.3/lib/honeybadger/exception_extensions.rb:10: stack level too deep (SystemStackError)

**Comment by dritir** [comment]
@elersong did you solve this?

**Comment by Brescia717** [comment]
The checked answer is the solution that worked for me.

http://stackoverflow.com/questions/26152964/better-errors-gem-not-working-in-local-browser-no-errors-visible

**Comment by neves** [comment]
Same here:
chrome has 99% of CPU's load.
Ruby 2.3
Rails 4.2.6
gem 'better_errors', '~> 2.1.1'
gem 'binding_of_caller', '~> 0.7.2'
thin 1.6.4

**Comment by TLmaK0** [comment]
BetterErrors::Middleware.allow_ip! "0.0.0.0/0" in config/environments/devlopment.rb fix the problem for me

**Comment by zires** [comment]
Feel sad... when errors occurred, the tab in chrome were unresponsive.....

**Comment by reallyordinary** [comment]
This is not working for me at all. Just installed, Rails 5.1, in the Gemfile's development group.

If there's an error on a page, BetterErrors loads and then hangs almost immediately. Freezes the browser tab. Requires a server restart. I tried the various solutions noted above and none worked.

**Comment by RobinDaugherty** [comment]
@reallyordinary it sounds like your issue is large variables, which isn't related to this issue. We've merged a change that should fix this, #360. Can you test your application with the master branch of better_errors and give us some feedback in #360?
