### ISSUE TITLE
Binding of caller not working on most basic rack application

### ISSUE THREAD

**Issue by CrowdHailer** [charliesome/better_errors#298]
I am trying to use better errors on a basic rack application. I cannot get the live REPL working. To test I have been using the following application

``` rb
require 'better_errors'
require 'binding_of_caller'

use BetterErrors::Middleware

run proc { |env| raise "something" }
```

This application shows the stack trace on the left. but none of the content on the right half of the screen

I have been trying this basic rack application after [raising this problem](https://github.com/Wardrop/Scorched/issues/31) in relation to the Scorched framework. However the example above shows it is not a Scorched problem

**Comment by pertunia** [comment]
How can we build that software we thout knowing each ather

**Comment by adaedra** [comment]
I have a similar issue. As sample above works in my case, it fails with the same results (missing right pane) if I put the use inside a `Rack::Builder`, like that:

```ruby
require 'better_errors'
require 'binding_of_caller'

app = Rack::Builder.new do
    use BetterErrors::Middleware
    run(proc { |env| raise "something" })
end

run app
```

The following stack trace is issued:

```
NoMethodError: undefined method `id' for nil:NilClass
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:127:in `internal_call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:75:in `better_errors_call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/adaedra/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
::1 - - [05/May/2015:13:07:39 +0200] "POST /__better_errors/088ca1ab9a48ffa6/variables HTTP/1.1" 500 52270 0.0300
```

I'm using ruby 2.2.2p95 under OS X. No difference if `binding_of_caller` is present or not.

PS: I commented on the previous issue as it seemed linked to – same problem. If the issue is different, I'll move it to another issue.

**Comment by umhan35** [comment]
Any follow-up? @charliesome

**Comment by cj** [comment]
I'm getting the exact same error.  Any update on this?

**Comment by alexanderadam** [comment]
I can't get it working with middleman either and I guess it's probably the samme issue as this one here.

**Comment by RobinDaugherty** [comment]
Using better_errors 2.3.0 the first example works correctly, and displays the variables in the right pane. 

The second example, using `Rack::Builder`, still encounters the `NoMethodError`:
```rb
app = Rack::Builder.new do
  use BetterErrors::Middleware
  run(proc { |env| raise "something" })
end

run app
```

The issue here has to do with the middleware stack. This fixes the issue:
```rb
use BetterErrors::Middleware

app = Rack::Builder.new do
  run(proc { |env| raise "something" })
end

run app
```

**Comment by adaedra** [comment]
There's effectively surely something in the way the middleware is inserted in the stack that puts better_errors in error, but I believe the position (or how deep in `Rack::Builder` instances you put it) should not influence the way the middleware works (middlewares are designed to be independent after all).

The use case could be to run multiple Rack applications at the same time, with only some affected by better_errors, which is basically what the code above goes for.

Moving the middleware “upper” is not a solution.

However, I realize that this is a slightly different case from the original described case. Yes, it works in the “most basic case”. Should we move this to an issue “Doesn't work in a nested `Rack::Builder`”?
