### ISSUE TITLE
NoMethodError at /__better_errors/xxxx/variables undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by zfjoy520** [charliesome/better_errors#301]
when I use better_errors work with Sinatra + Grape, it not works

my code is:

```
# configure.rb file
class Configure < Sinatra::Base
  configure :development do
    use BetterErrors::Middleware
    BetterErrors.application_root = __dir__
  end
end
```

```
# dashboard.rb file
class Dashboard < Sinatra::Base
  use Configure

  get('/') { raise }
end
```

```
# apiv1.rb file
class APIv1 < Grape::API
  format :json

  resource do
    get :test do
      raise
    end
  end

end
```

```
# config.ru file
require 'sinatra'
require 'grape'
require 'better_errors'

class Admin < Sinatra::Base
  use Dashboard
end

class API < Grape::API
  use BetterErrors::Middleware
  mount APIv1 => '/api/v1'
end

run Rack::Cascade.new [API, Admin]
```

when i visit: http://0.0.0.0:9292/api/v1/test first
APIv1 class raise an error, it works, the left is ok, but when i click a left section, the right deteils not work.

and then visit: http://0.0.0.0:9292
Dashboard class raise an error, it works, the left list and right details is ok.

it has an error, the details is:

```
NoMethodError at /__better_errors/0e1adbe07252ede1/variables
undefined method `id' for nil:NilClass
file: middleware.rb location: internal_call line: 127
```

and i view the code, and found:

```
    def internal_call(env, opts)
      if opts[:id] != @error_page.id
        return [200, { "Content-Type" => "text/plain; charset=utf-8" }, [JSON.dump(error: "Session expired")]]
      end

      env["rack.input"].rewind
      response = @error_page.send("do_#{opts[:method]}", JSON.parse(env["rack.input"].read))
      [200, { "Content-Type" => "text/plain; charset=utf-8" }, [JSON.dump(response)]]
    end
```

the @error_page is nil

and the second, when i first visit: http://0.0.0.0:9292 and then visit http://0.0.0.0:9292/api/v1/test

the error not occur any more, it just return an json: {"error":"Session expired"}

please help

**Comment by zfjoy520** [comment]
visit http://0.0.0.0:9292/api/v1/test first
![image](https://cloud.githubusercontent.com/assets/91816/6994933/8a8dca58-db5d-11e4-9552-290a4e763156.png)

and visit http://0.0.0.0:9292
![image](https://cloud.githubusercontent.com/assets/91816/6994926/5a419370-db5d-11e4-81d0-471142073072.png)

and then
visit http://0.0.0.0:9292 first
![image](https://cloud.githubusercontent.com/assets/91816/6994926/5a419370-db5d-11e4-81d0-471142073072.png)

visit http://0.0.0.0:9292/api/v1/test again
![image](https://cloud.githubusercontent.com/assets/91816/6994941/cdccdc14-db5d-11e4-8f28-b8ab73144313.png)

![image](https://cloud.githubusercontent.com/assets/91816/6994943/df4b6c44-db5d-11e4-852c-20b713ee391b.png)

**Comment by hakunin** [comment]
I might be experiencing similar issue ![screen shot 2015-10-28 at 16 07 30](https://cloud.githubusercontent.com/assets/65846/10792702/13f04758-7d8e-11e5-8bef-c2cabb81cb63.png)

**Comment by mtwilliams** [comment]
I'm getting this too :sob:

**Comment by hakunin** [comment]
I think I might have been using a node.js redirect there to the actual rails app. Not 100% sure though.

**Comment by mtwilliams** [comment]
I've figured it out, at least for my case: a new `BetterErrors::Middleware` instance is being created for every request. This means `@error_page` will be `nil` for any subsequent `internal_call`. The quick 'n' dirty solution is to instantiate a single instance and reuse it across all requests.

Here's how I did it:

```Ruby
class BetterErrors::Middleware::Proxy
  @@middleware = BetterErrors::Middleware.new(proc {|env| @@app.call(env)})
  def initialize(app); @@app = app; end
  def call(env); @@middleware.call(env); end
end
```

Hope it helps!

**Comment by bfaloona** [comment]
I can repro this bug running a .ru file with shotgun, but the issue does not repro when run with rackup.

Expected: REPL renders in browser.
Actual: REPL does not render. Server returns 500.

```ruby
# config.ru
require 'better_errors'
require 'binding_of_caller'
class RackApp
  def self.call(env)
    raise 'Better Errors Issue #301'
  end
end
use BetterErrors::Middleware
run RackApp
```

Running with rackup works fine and does not repro the bug:
```bash
$ rackup config.ru
```

Running with shotgun repros the bug:
```bash
$ shotgun config.ru
```

Call Stack:
```bash
$ shotgun config.ru 
== Shotgun/Thin on http://127.0.0.1:9393/
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 127.0.0.1:9393, CTRL+C to stop
127.0.0.1 - - [09/Jan/2016:13:40:55 -0800] "GET / HTTP/1.1" 500 - 0.0057
NoMethodError: undefined method `id' for nil:NilClass
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:127:in `internal_call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:75:in `better_errors_call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
	/Users/brandon/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/bin/shotgun:162:in `<top (required)>'
	/Users/brandon/.rvm/gems/ruby-2.2.1/bin/shotgun:23:in `load'
	/Users/brandon/.rvm/gems/ruby-2.2.1/bin/shotgun:23:in `<main>'
	/Users/brandon/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/brandon/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
127.0.0.1 - - [09/Jan/2016:13:40:55 -0800] "POST /__better_errors/c38cbebe20df9bc5/variables HTTP/1.1" 500 88270 0.0248
```

Ruby / Gem Environment:
```bash
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

$ gem list
(truncated)
better_errors (2.1.1)
binding_of_caller (0.7.2)
bundler (1.10.6)
pry (0.10.3)
rack (1.6.4, 1.6.0, 1.5.5, 1.5.3)
rack-contrib (1.4.0)
rake (10.4.2, 10.1.1, 0.9.2.2)
shotgun (0.9.1)
thin (1.5.1)

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/brandon/.rvm/gems/ruby-2.2.1
  - RUBY EXECUTABLE: /Users/brandon/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/brandon/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/brandon/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/brandon/.rvm/gems/ruby-2.2.1
     - /Users/brandon/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/brandon/.rvm/gems/ruby-2.2.1/bin
     - /Users/brandon/.rvm/gems/ruby-2.2.1@global/bin
     - /Users/brandon/.rvm/rubies/ruby-2.2.1/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/brandon/.rvm/bin
```

**Comment by grekko** [comment]
@mtwilliams I did not find any `class BetterErrors::Middleware::Proxy`-class in the current release of better_errors (2.2.1) – which is why this unfortunately did not help me.

To get this working I hacked together the following (hopefully temporary) [fork](https://github.com/grekko/better_errors) of better_errors. My only [change](https://github.com/grekko/better_errors/commit/c557196a2602f2186fa5ed3f52de97f074ebb4ed) is to store the `@error_page` object on the `BetterErrors::Middleware`-class for further inspection in subsequent requests.

I'd love to get some feedback of you guys if it fixes your problem and maybe @charliesome can jump in and help out wether this is a good idea in general.

Just use [my repo](https://github.com/grekko/better_errors) in your Gemfile to give it a shot:

~~~ruby
gem 'better_errors', github: 'grekko/better_errors'
~~~

**Comment by mtwilliams** [comment]
@grekko hmm? `BetterErrors::Middleware::Proxy` is my quick 'n' dirty hack... not a class provided by BetterErrors. It achieves what you do, but by reusing the `BetterErrors::Middleware` instance.

**Comment by grekko** [comment]
@mtwilliams Ah! Please excuse my confusion. Now that I am *holding it right* I can see that your proposal is much less invasive.

**Comment by mtwilliams** [comment]
No worries @grekko :)

**Comment by brauliobo** [comment]
thanks @grekko, your fork works! maintainers, can you please evaluate upstreaming the fix or adding new maintainers?

**Comment by awolfson** [comment]
@mtwilliams I am getting `wrong number of arguments (0 for 1..2)` when I dump your fix into a `config/initializers` file. Am I not using it in the right place? It doesn't look like there have been any changes to the `BetterErrors::Middleware#initialize` method since you posted your fix, so I'm not sure why it should take a block. Let me know what I'm doing wrong? 😄

**Comment by mtwilliams** [comment]
@awolfson the block is to grab scope, so it can access `@@app`. Has there been a change to `BetterErrors::Middleware#initialize` such that it no longer accepts blocks?

**Comment by mtwilliams** [comment]
Doesn't look like it. In retrospect, that would break the Rack middleware contract, so there's no way that's the case.

@awolfson how are you setting up your middleware? You should be using `BetterErrors::Middleware::Proxy` in place of `BetterErrors::Middleware`.

**Comment by awolfson** [comment]
@mtwilliams Yeah, I am swapping it out in `config/environments/development.rb`:

```ruby
config.middleware.swap BetterErrors::Middleware, BetterErrors::Middleware::Proxy
```

I think it chokes before getting to that point, anyway.

**Comment by mtwilliams** [comment]
@awolfson is Rails' middleware not passing an `app` argument? Can you provide a callstack?

**Comment by awolfson** [comment]
@mtwilliams Sorry, that would help, huh!

Here's the relevant part:
```
/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:46:in `initialize': wrong number of arguments (0 for 1..2) (ArgumentError)
```

That's coming from this line:
```ruby
  @@middleware = BetterErrors::Middleware.new {|env| @@app.call(env)}
```

**Comment by mtwilliams** [comment]
@awolfson Odd. What if you try passing it a block rather than a Proc?

**Comment by awolfson** [comment]
@mtwilliams I tried it, plus a whole bunch of other configurations. I wonder if the problem is the calling context. What location do you have that code in, and where are you loading it?

**Comment by mtwilliams** [comment]
@awolfson I don't use Rails; so I can't help you there.

**Comment by mikezter** [comment]
I had this issue in a Rails 4.2 app and it was solved by removing the line 
` config.middleware.use BetterErrors::Middleware` from `config/development.rb`.

**Comment by awolfson** [comment]
@mikezter That just means you aren't using `BetterErrors` at all anymore.

**Comment by RobinDaugherty** [comment]
This error was caused by a missing check for the existence of a previously-caught exception. I believe the exception will no longer be thrown because we now check for a missing session (#375). We also check for a failure in the XHR, so a more useful error message will be shown instead of a blank frame (#389).

There are still conditions under which variable information won't be available, such as when the server process has been restarted.
