### ISSUE TITLE
No work if server is bind to ip

### ISSUE THREAD

**Issue by obelich** [charliesome/better_errors#307]
Hiyas im working in development but i up the server wit 

rails s -b 192.168.1.29 

and better errors is not showin any more show the basic rails error

sorry english bad :(

**Comment by charliesome** [comment]
Only `127.0.0.0/8` and `::1` are allowed to access the better_errors page by default:

https://github.com/charliesome/better_errors/blob/master/lib/better_errors/middleware.rb#L39-40

When you're accessing your development server via a 192.168.x.x address that also forces the source address of the connection to be a 192.168.x.x address.
