### ISSUE TITLE
BetterErrors enabled during tests

### ISSUE THREAD

**Issue by fgarcia** [charliesome/better_errors#309]
I am having better_errors content in my Rspec runs because the middleware is inserted in test mode. Is this the expected default? 

I hacked the code to load the middleware only in development, is there a reason to have a full better_errors report during testing?

```
def use_better_errors?
  # !Rails.env.production? and app.config.consider_all_requests_local
  Rails.env.development?
end
```

**Comment by guizmaii** [comment]
:+1:

**Comment by jodosha** [comment]
Same problem here. BetterErrors swallows the exceptions coming from a non-Rails HTTP API endpoint during the tests.

**Comment by bquorning** [comment]
As the README says, only bundle the gem in development:
```rb
group :development do
  gem "better_errors"
end
```
