### ISSUE TITLE
integrate with atom?

### ISSUE THREAD

**Issue by macool** [charliesome/better_errors#314]
I'd be happy to help

**Comment by zedtux** [comment]
+1

**Comment by taboularasa** [comment]
@charliesome if you can confirm that PR implementing this feature would be welcome and could maybe advise on the best strategy I would be interested in implementing this.

**Comment by charliesome** [comment]
:+1: for a pull request adding atom `EDITOR` support.

I'm hesitant about adding any deeper integration - Better Errors as a project is basically done these days and I'm not sure if I want to add any new features.

**Comment by pablocrivella** [comment]
+1

**Comment by mibamur** [comment]
resolved https://github.com/charliesome/better_errors/issues/339

**Comment by zedtux** [comment]
@mibamur thank you it's working.

Here is the step-by-step:

 1. Download [atom-handler](https://github.com/WizardOfOgz/atom-handler/releases/download/1.1.1/atom-handler.app.zip) (it is not available in the Atom package manager)
 2. Move it to the /Applications folder
 3. Right click it and choose **Open**
 4. Click the **Open** button
 5. Create the file `config/initializers/better_errors.rb` and put the following content:

   ```
   require 'better_errors'

   BetterErrors.editor = 'atm://open?url=file://%{file}&line=%{line}'
   ```
 6. Restart your Rails server and you're done.

**Comment by eclemens** [comment]
For UBUNTU/LINUX users:

Here is the step-by-step:

1. Download and install [atom-handler](https://github.com/eclemens/atom-url-handler) (it is not available in the Atom package manager)
2. Create the file config/initializers/better_errors.rb and put the following content:
    ```
    require 'better_errors'

    BetterErrors.editor = 'atm://open?url=file://%{file}&line=%{line}'
    ```
3. Restart your Rails server and you're done.

**Comment by RobinDaugherty** [comment]
Instructions are now [in the wiki](https://github.com/charliesome/better_errors/wiki/Link-to-your-editor#atom).
