### ISSUE TITLE
Why it does not work live console (the box) on jruby ?

### ISSUE THREAD

**Issue by jancuk** [charliesome/better_errors#321]
is it possible to enable the live console of better_errors in jruby ? Why it does not work out the box?

list :
jruby-9.0.0.0.pre1
binding_of_caller (0.7.3.pre1)
better_errors (2.1.1)
rails (= 4.2.4)

![error](https://cloud.githubusercontent.com/assets/1078788/11265630/642222b6-8ed0-11e5-9a65-6daaa07692c1.png)

**Comment by charliesome** [comment]
binding_of_caller does not work on JRuby

**Comment by Xosmond** [comment]
I have Ruby 2.3.0 and have the same problem
