### ISSUE TITLE
original_exception is deprecated with Rails 5

### ISSUE THREAD

**Issue by hoahm** [charliesome/better_errors#333]
I got these warning when integrating better_errors with Rails 5

    DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
    DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)

**Comment by richpeck** [comment]
+1

**Comment by connorshea** [comment]
:+1: ran into the same issue

**Comment by connorshea** [comment]
@charliesome any updates on fixing this?

**Comment by bimovidia** [comment]
+1

**Comment by SicutDominus** [comment]
+1

**Comment by danmayer** [comment]
fix looks good

**Comment by grosser** [comment]
FYI

```Ruby
config.active_support.deprecation = -> (message, _backtrace) do
  if message.include?("#original_exception is deprecated")
      # ignored until https://github.com/charliesome/better_errors/issues/333
    else
      raise message
    end
  end
```
