### ISSUE TITLE
error on try open url handler sublime  

### ISSUE THREAD

**Issue by bperucchi** [charliesome/better_errors#337]
When I clicked on URL Handler to open sublime on stack error if the document.

this path freeze my sublime -  this is not my project path
subl://open?url=file:///Users/brenoperucchi/rbenv/versions2.2.0/gemsets/imentore/gems/activemodel-4.0.13/lib/active_model/attribute_methods.rb&line=439

not freeze my sublime -  this is my project path
subl://open?url=file:///Users/brenoperucchi/Google-Drive/03-Apps/imentore/imentore-ecommerce/app/models/imentore/image.rb&line=13

event logging - stack error
https://drive.google.com/file/d/0B7NFAQ1jLJ1qeS1CaGdfd0JzaDQ/view?usp=sharing

I don't know if this error is different from sublime or be2err or neither both

**Comment by bperucchi** [comment]
Please close this issues because I found what is hurt the sublime. Was the ApplySyntax that was freezing.

**Comment by joshuapaling** [comment]
@bperucchi you should be able to close the issue yourself I believe?
