### ISSUE TITLE
How to open in Atom editor?

### ISSUE THREAD

**Issue by jmuheim** [charliesome/better_errors#339]
I recently switched from TextMate to Atom. Now I'm missing the possibility to open files directly when clicking on their names on an error page.

The gem `xray-rails` offers an easy option to set the path to the editor, like this:

![image](https://cloud.githubusercontent.com/assets/1814983/13007923/97da6ed2-d193-11e5-928f-6d0133123dd9.png)

Maybe this would be a better solution? Then every developer can specify easily his own preference.

**Comment by vortizhe** [comment]
I use https://github.com/WizardOfOgz/atom-handler

**Comment by jmuheim** [comment]
Perfect, this solves the problem for me.

**Comment by cenotaph** [comment]
Any idea how to STOP opening in atom once you've installed the atom-handler app?
