### ISSUE TITLE
/__better_errors not working

### ISSUE THREAD

**Issue by willcosgrove** [charliesome/better_errors#353]
Ever since rails/rails@266455cf25aba942b8717ceb0269d66f719b5696 the `/__better_errors` endpoint has been broken.

The changes [here](https://github.com/rails/rails/commit/266455cf25aba942b8717ceb0269d66f719b5696#diff-7a283d03093301fecfe4dca46dc37c2cR109) and [here](https://github.com/rails/rails/commit/266455cf25aba942b8717ceb0269d66f719b5696#diff-7a283d03093301fecfe4dca46dc37c2cL117) make it so that instantiating an `ActionDispatch::ExceptionWrapper` with a `nil` in place of the `exception` will result in a 💥 

Which is exactly what happens [when you go to `/__better_errors`](https://github.com/charliesome/better_errors/blob/d285ecf7f78909b026ee7d64ca4764ce53340e25/lib/better_errors/middleware.rb#L77)

``` ruby
when %r{/__better_errors/?\z}
  show_error_page env
```

``` ruby
def show_error_page(env, exception=nil)
  # ...
  if defined? ActionDispatch::ExceptionWrapper
    status_code = ActionDispatch::ExceptionWrapper.new(env, exception).status_code
  end
  # ...
end
```

I don't know whether it's the fault of rails for changing the internals of `ActionDispatch::ExceptionWrapper`, or if `exception` should have always been non-`nil`, in which case it's better_error's bug.

What do you think @charliesome?  Should I submit a PR here to fix this, or should I take this up with Rails?

**Comment by vala** [comment]
Since this has not been answered for more than 5 months, I put up a simple snippet to patch my apps thanks to @willcosgrove indications.

You can use it until the issue is answered. 

Put the following in an initializer or in a lib file and require it on startup : 

```ruby
module BetterErrors
  class Middleware
    def show_error_page(env, exception=nil)
      type, content = if @error_page
        if text?(env)
          [ 'plain', @error_page.render('text') ]
        else
          [ 'html', @error_page.render ]
        end
      else
        [ 'html', no_errors_page ]
      end

      status_code = 500

      [status_code, { "Content-Type" => "text/#{type}; charset=utf-8" }, [content]]
    end
  end
end
```

**Comment by mutantkeyboard** [comment]
Confirmed. 
@vala 's code is working and should be included in the patch.

**Comment by RobinDaugherty** [comment]
The exception being raised is `undefined method 'cause' for nil:NilClass`.

@willcosgrove thanks for opening this issue so it could be tracked down. Just want to let you know that if you had mentioned the text of the exception, it would have been much more helpful.

**Comment by RobinDaugherty** [comment]
Version 2.2.0 of the gem has been released, so this issue seems to be fixed.

**Comment by mnd-dsgn** [comment]
For anyone upgrading, changing the version in the Gemfile to `gem 'better_errors', '~> 2.2.0' and bundling was the only way I could upgrade, upgrading from the command line game me a 'Your Rack app raised an exception when Pow tried to run it. TypeError: superclass must be a Class (Module given)' error.
