### ISSUE TITLE
Push update to rubygems

### ISSUE THREAD

**Issue by serggl** [charliesome/better_errors#357]
is it possible to push an update to rubygems?  
#354 was merged and I would like to have it in my project.

Thanks!

**Comment by yjukaku** [comment]
👍  This is quite confusing. A lot of work has been done on master that I was missing out on 😄 

@charliesome Any chance of this happening, or anything holding it up? Thanks!

**Comment by hut8** [comment]
@charliesome Any way that this can be done? Thanks for the gem 😄

**Comment by rubendinho** [comment]
was also wondering if there's an update to this

**Comment by RobinDaugherty** [comment]
2.2.0 has been released!
