### ISSUE TITLE
'variables' apiCall is failling for root page

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [charliesome/better_errors#359]
Hi, thx for such a nice gem!!!

My Rack app is doing ok with better_errors. But for root page env['SCRIPT_NAME'] == '/' and xhr call to 'variables' results to 'http://_better_errors/...' which is failing.

**Comment by RobinDaugherty** [comment]
Under some conditions when there is a large amount of data in local variables, the call to get variables can take a very long time, or even time out. There is a proposal to improve this with #360.
