### ISSUE TITLE
clarification of security warning

### ISSUE THREAD

**Issue by BKSpurgeon** [charliesome/better_errors#374]
Hi there

thank you all for your work on this wonderful tool.

a question about what is written in the documentation:

> NOTE: It is critical you put better_errors in the development section. Do NOT run better_errors in production, or on Internet facing hosts.

What is meant by "internet facing hosts"? Any clarificaiton would be much appreciated.

rgds

Ben

**Comment by RobinDaugherty** [comment]
An "Internet-facing host" is a server that has a public address and is accessible to other hosts over the Internet.
