### ISSUE TITLE
Erubi superclass mismatch with Haml

### ISSUE THREAD

**Issue by dguettler** [charliesome/better_errors#396]
### Error description
Attempting to run a Rails application with version 2.3.0 results in the following error
```
.bundle/ruby/2.4.0/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:5: warning: toplevel constant Erubi referenced by ActionView::Template::Handlers::ERB::Erubi
rails aborted!
TypeError: superclass must be a Class (Module given)
.bundle/ruby/2.4.0/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:5:in `<module:Haml>'
.bundle/ruby/2.4.0/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:4:in `<top (required)>'
.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:293:in `require'
.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:293:in `block in require'
```

### Possible other conflicting dependencies
- Haml

### Affected version
- 2.3.0

### Not affected version
- 2.2.0

**Comment by dguettler** [comment]
Cross-linking https://github.com/haml/haml/issues/946

**Comment by RobinDaugherty** [comment]
@dguettler can you test adding Erubis directly to your Gemfile? It seems like it might be caused by the complete removed of Erubis.

**Comment by tmnsun** [comment]
@RobinDaugherty adding Erubis to Gemfile solves the issue.

**Comment by RobinDaugherty** [comment]
This is an incompatibility of haml when erubi is in bundle with Rails prior to 5.1. I've submitted https://github.com/haml/haml/pull/948 to fix this. Can you try using my fork of haml in your project and report your results in that pull request?

```
gem 'haml', github: 'RobinDaugherty/haml', branch: 'patch-1'
```

**Comment by dguettler** [comment]
@RobinDaugherty adding Erubis did not solve the issue for me.
Your `patch-1` branch works fine though. Thanks again for digging into this.

**Comment by RobinDaugherty** [comment]
haml version 5.0.2 includes a fix for Erubi with older versions of Rails.
