### ISSUE TITLE
Impossible to get access or modify maximum_variable_inspect_size

### ISSUE THREAD

**Issue by thibaut-poullain** [charliesome/better_errors#408]
Hi there, 

I'm on rails 5.1.3 and ruby 2.4.1p111 and better errors install as specified in the doc.

My browser is slow because of the size of some variables, I try to reduce the maximum size.

I get this :

> [5] pry(main)> BetterErrors.maximum_variable_inspect_size
NoMethodError: undefined method `maximum_variable_inspect_size' for BetterErrors:Module
from (pry):5:in `__pry__'

Why ?? ;) 

Thx a lot !

**Comment by RobinDaugherty** [comment]
@thibaut-poullain the feature you're trying to use has not been released yet. If you use the latest version of the master branch, you'll be able to test it. Change your Gemfile to:

```rb
gem 'better_errors', github: 'charliesome/better_errors'
```

Please give that a test and report back whether the new version works for you.

**Comment by thibaut-poullain** [comment]
It works that way :) 

However, it shows :

> (object too large. Modify ActionDispatch::Request::Session#inspect or increase BetterErrors.maximum_variable_inspect_size)

Would it be possible to truncate the variable based on the maximum_variable_inspect_size instead of preventing it to be showned ?

Just an idea :)

Thx a lot !

**Comment by RobinDaugherty** [comment]
That might be possible, but not sure how slow that would be.
